small changes

diff --git a/.github/workflows/pr-checks.yml b/.github/workflows/pr-checks.yml
--- a/.github/workflows/pr-checks.yml
+++ b/.github/workflows/pr-checks.yml
@@ -43,6 +43,11 @@ jobs:
         id: test
         continue-on-error: true
       
+      - name: Run build
+        run: pnpm build
+        id: build
+        continue-on-error: true
+      
       - name: Check results
         run: |
           if [ "${{ steps.biome.outcome }}" == "failure" ]; then
@@ -57,5 +62,12 @@ jobs:
             exit 1
           else
             echo "✅ Tests passed"
+          fi
+          
+          if [ "${{ steps.build.outcome }}" == "failure" ]; then
+            echo "❌ Build failed"
+            exit 1
+          else
+            echo "✅ Build passed"
           fi
         shell: bash
